// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Safnow.Model;

namespace Safnow.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20200515192418_migration")]
    partial class migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Safnow.Model.Alerta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("UsuarioIdentifier")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioIdentifier");

                    b.ToTable("Alertas");
                });

            modelBuilder.Entity("Safnow.Model.Ubication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AlertaId")
                        .HasColumnType("int");

                    b.Property<string>("Altitude")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Latitude")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("AlertaId")
                        .IsUnique();

                    b.ToTable("Ubications");
                });

            modelBuilder.Entity("Safnow.Model.Usuario", b =>
                {
                    b.Property<string>("Identifier")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("varchar(9) CHARACTER SET utf8mb4")
                        .HasMaxLength(9);

                    b.Property<bool>("Verificated")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("VerificationCode")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Identifier");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Safnow.Model.VerificationCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("varchar(5) CHARACTER SET utf8mb4")
                        .HasMaxLength(5);

                    b.HasKey("Id");

                    b.ToTable("Codes");
                });

            modelBuilder.Entity("Safnow.Model.Alerta", b =>
                {
                    b.HasOne("Safnow.Model.Usuario", "Usuario")
                        .WithMany("Alertas")
                        .HasForeignKey("UsuarioIdentifier")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Safnow.Model.Ubication", b =>
                {
                    b.HasOne("Safnow.Model.Alerta", "Alert")
                        .WithOne("Ubication")
                        .HasForeignKey("Safnow.Model.Ubication", "AlertaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
