// <auto-generated />
using System;
using Escuela2019.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Escuela2019.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20200219095734_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Escuela2019.Model.Alerta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Direction")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("UsuarioIdentifier")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioIdentifier");

                    b.ToTable("Alertas");
                });

            modelBuilder.Entity("Escuela2019.Model.Ubication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AlertId")
                        .HasColumnType("int");

                    b.Property<string>("Altitude")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Latitude")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("AlertId");

                    b.ToTable("Ubications");
                });

            modelBuilder.Entity("Escuela2019.Model.Usuario", b =>
                {
                    b.Property<string>("Identifier")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("varchar(9) CHARACTER SET utf8mb4")
                        .HasMaxLength(9);

                    b.Property<bool>("Verificated")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("VerificationCode")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Identifier");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Escuela2019.Model.VerificationCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("varchar(5) CHARACTER SET utf8mb4")
                        .HasMaxLength(5);

                    b.HasKey("Id");

                    b.ToTable("Codes");
                });

            modelBuilder.Entity("Escuela2019.Model.Alerta", b =>
                {
                    b.HasOne("Escuela2019.Model.Usuario", "Usuario")
                        .WithMany("Alertas")
                        .HasForeignKey("UsuarioIdentifier")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Escuela2019.Model.Ubication", b =>
                {
                    b.HasOne("Escuela2019.Model.Alerta", "Alert")
                        .WithMany("Ubications")
                        .HasForeignKey("AlertId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
